[project]
name = "govsgtrustedsites"
version = "0.0.1"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.2",
    "beautifulsoup4>=4.14.2",
    "fake-useragent>=2.2.0",
    "lxml>=6.0.2",
    "more-itertools>=10.8.0",
    "tldextract>=5.3.0",
]
